### ISSUE TITLE
compatible with asgi_lifespan

### ISSUE THREAD

**Issue by mosi-kha** [uriyyo/fastapi-lifespan-manager#144] opened 2024-02-22 14:00 UTC
Hi
first, thanks for maintain this tool,
i used asgi_lifespan for handle async tests, after use this package for separate my lifespans I've get error:
`RuntimeError: The server does not support "state" in the lifespan scope.`
what should i do?

**Comment by uriyyo** [comment] 2024-02-26 10:22
Hi @mosi-kha,

Could you please show a code example so I can reproduce this issue?

**Comment by nike4192** [comment] 2024-03-06 04:52
Same problem
```
INFO:     Started server process [63]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in lifespan
    raise RuntimeError(
RuntimeError: The server does not support "state" in the lifespan scope.

ERROR:    Application startup failed. Exiting.
```

`/usr/local/lib/python3.10/site-packages/starlette/routing.py`
```python
class Router:
...
    async def lifespan(self, scope: Scope, receive: Receive, send: Send) -> None:
        """
        Handle ASGI lifespan messages, which allows us to manage application
        startup and shutdown events.
        """
        started = False
        app: typing.Any = scope.get("app")
        await receive()
        try:
            async with self.lifespan_context(app) as maybe_state:
                if maybe_state is not None:
                    if "state" not in scope:
680 ->                  raise RuntimeError(
                            'The server does not support "state" in the lifespan scope.'
                        )
                    scope["state"].update(maybe_state)
                await send({"type": "lifespan.startup.complete"})
                started = True
                await receive()
        ...
```

I try `AsyncIterator` and just `Iterator`, but nothing has changed

`.../postgres.py`
```python
def setup_db(app: FastAPI) -> Iterator[State]:
    postgres_db.connect()

    yield {"postgres_db": postgres_db}

    postgres_db.close()
```

`.../sqlite.py`
```python
def setup_db(app: FastAPI) -> Iterator[State]:
    sqlite_db.connect()
    sqlite_db.create_tables(TABLES_TO_CREATE)

    yield {"sqlite_db": sqlite_db}

    sqlite_db.close()
```

And use it

`.../lifespan.py`
```python
from ....sqlite import setup_db as setup_sqlite_db
from ....postgres import setup_db as setup_postgres_db

manager = LifespanManager()

manager.add(setup_sqlite_db)
manager.add(setup_postgres_db)

app = FastAPI(lifespan=manager)
```

`requirements.txt`
```
...
fastapi==0.104.1
fastapi-lifespan-manager==0.1.4
fastapi_camelcase==2.0.0
starlette==0.27.0
...
```

Python 3.10.13
pip 23.0.1

---

Maybe the problem is using RouterAPI?

**Comment by uriyyo** [comment] 2024-03-12 09:45
Hmm, looks interesting, I will take a look

**Comment by uriyyo** [comment] 2024-03-12 20:32
@nike4192 @mosi-kha Which version of uvicorn you are using? It should be >=0.21.0

**Comment by nike4192** [comment] 2024-03-12 21:05
@uriyyo
Yes, you are right, thanks

I just updated `uvicorn` from 0.20.0 to 0.21.0 and it worked.

> main.py

```py
@manager.add
async def something1(app: FastAPI):
    logger.critical('startup 1')

    yield

    logger.critical('shutdown 1')


@manager.add
async def something2(app: FastAPI):
    logger.critical('startup 2')

    yield

    logger.critical('shutdown 2')
```


> output

```log
INFO:     Application shutdown complete.
INFO:     Finished server process [50]
INFO:     Started server process [53]
INFO:     Waiting for application startup.
DEBUG:    startup 1
DEBUG:    startup 2
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
DEBUG:    shutdown 2
DEBUG:    shutdown 1
```

**Comment by uriyyo** [comment] 2024-03-12 21:11
Great, I guess @mosi-kha has the same issue, but let's wait for his reply.

**Comment by uriyyo** [comment] 2024-03-22 23:24
@mosi-kha Any updates?

**Comment by uriyyo** [comment] 2024-07-14 10:47
@mosi-kha I'm closing this issue. Please, reopen it in case if this issue still exists.

**Closed by uriyyo** 2024-07-14 10:47 UTC
Labels: bug, question
